create table if not exists students (
  id text primary key,
  name text not null,
  status text default 'Enrolled',
  program text,
  department text,
  batch text,
  section text,
  study_year text,
  admission_date date,
  dob date,
  birth_place text,
  blood_group text,
  national_id text,
  religion text,
  father_name text,
  mother_name text,
  present_address text,
  permanent_address text,
  mobile text,
  guardian_phone text,
  email text,
  access_key text not null,
  cgpa text,
  payment text default 'Due',
  results text,
  photo text,
  education jsonb default '[]'::jsonb,
  core text,
  major text,
  second_major text,
  minor text,
  registered_credits text,
  completed_credits text,
  curriculum_courses jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  created_at timestamptz default now()
);

create table if not exists results (
  id bigint generated by default as identity primary key,
  student_id text references students(id) on delete cascade,
  semester text,
  course_code text,
  course_title text,
  grade text,
  gpa numeric,
  created_at timestamptz default now()
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  student_id text references students(id) on delete cascade,
  semester text,
  amount numeric default 0,
  status text default 'Due',
  receipt_no text,
  created_at timestamptz default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  student_id text references students(id) on delete cascade,
  course_code text,
  present_count integer default 0,
  total_class integer default 0,
  created_at timestamptz default now()
);

create table if not exists course_registrations (
  id bigint generated by default as identity primary key,
  student_id text references students(id) on delete cascade,
  semester text,
  courses jsonb default '[]'::jsonb,
  status text default 'Pending',
  created_at timestamptz default now()
);

create table if not exists certificate_requests (
  id bigint generated by default as identity primary key,
  student_id text references students(id) on delete cascade,
  certificate_type text,
  status text default 'Pending',
  note text,
  created_at timestamptz default now()
);

alter table students enable row level security;
alter table notices enable row level security;
alter table results enable row level security;
alter table payments enable row level security;
alter table attendance enable row level security;
alter table course_registrations enable row level security;
alter table certificate_requests enable row level security;

drop policy if exists "public read students" on students;
drop policy if exists "public write students demo" on students;
drop policy if exists "public read notices" on notices;
drop policy if exists "public write notices demo" on notices;
drop policy if exists "public read results" on results;
drop policy if exists "public read payments" on payments;
drop policy if exists "public read attendance" on attendance;
drop policy if exists "public read registrations" on course_registrations;
drop policy if exists "public read certificate requests" on certificate_requests;

create policy "public read students" on students for select using (true);
create policy "public write students demo" on students for all using (true) with check (true);
create policy "public read notices" on notices for select using (true);
create policy "public write notices demo" on notices for all using (true) with check (true);
create policy "public read results" on results for select using (true);
create policy "public read payments" on payments for select using (true);
create policy "public read attendance" on attendance for select using (true);
create policy "public read registrations" on course_registrations for select using (true);
create policy "public read certificate requests" on certificate_requests for select using (true);
